# GeMM
gemm_thread_ram = [ 'gemm', 'gemm_ram', 'gemm_thread_ram' ]
gemm_stream_ram = [ 'gemm', 'gemm_ram', 'gemm_stream', 'gemm_stream_ram' ]
gemm_parallel_ram = [ 'gemm', 'parallel', 'gemm_parallel', 'gemm_parallel_ram' ]
gemm_blocked_ram = [ 'gemm', 'parallel', 'gemm_blocked', 'gemm_blocked_ram' ]
gemm_thread_pipo = [ 'gemm', 'gemm_pipo', 'gemm_thread_pipo' ]
gemm_stream_pipo = [ 'gemm', 'gemm_pipo', 'gemm_stream', 'gemm_stream_pipo' ]
gemm_parallel_pipo = [ 'gemm', 'parallel', 'gemm_parallel', 'gemm_parallel_pipo' ]
gemm_blocked_pipo = [ 'gemm', 'parallel', 'gemm_blocked', 'gemm_blocked_pipo' ]
gemm_thread_buffet = [ 'gemm', 'gemm_buffet', 'gemm_thread_buffet' ]
gemm_stream_buffet = [ 'gemm', 'gemm_buffet', 'gemm_stream', 'gemm_stream_buffet' ]
gemm_parallel_buffet = [ 'gemm', 'parallel', 'gemm_parallel', 'gemm_parallel_buffet' ]
gemm_blocked_buffet = [ 'gemm', 'parallel', 'gemm_blocked', 'gemm_blocked_buffet' ]

# SpMM
spmm_thread_ram = [ 'spmm', 'spmm_ram', 'spmm_thread_ram' ]
spmm_stream_ram = [ 'spmm', 'spmm_ram', 'spmm_stream', 'spmm_stream_ram' ]
spmm_parallel_ram = [ 'spmm', 'parallel', 'spmm_parallel', 'spmm_parallel_ram' ]
spmm_thread_pipo = [ 'spmm', 'spmm_pipo', 'spmm_thread_pipo' ]
spmm_stream_pipo = [ 'spmm', 'spmm_pipo', 'spmm_stream', 'spmm_stream_pipo' ]
spmm_parallel_pipo = [ 'spmm', 'parallel', 'spmm_parallel', 'spmm_parallel_pipo' ]
