# GeMM
gemm_thread_ram = [ 'gemm', 'gemm_ram', 'gemm_thread_ram' ]
gemm_stream_ram = [ 'gemm', 'gemm_ram', 'gemm_stream', 'gemm_stream_ram' ]
gemm_parallel_ram = [ 'gemm', 'gemm_parallel_ram' ]
gemm_thread_pipo = [ 'gemm', 'gemm_pipo', 'gemm_thread_pipo' ]
gemm_stream_pipo = [ 'gemm', 'gemm_pipo', 'gemm_stream', 'gemm_stream_pipo' ]

# SpMM
spmm_thread_ram = [ 'spmm', 'spmm_ram', 'spmm_thread_ram' ]
spmm_stream_ram = [ 'spmm', 'spmm_ram', 'spmm_stream_ram' ]
spmm_parallel_ram = [ 'spmm', 'spmm_parallel_ram' ]
spmm_thread_pipo = [ 'spmm', 'spmm_pipo', 'spmm_thread_pipo' ]
