# GeMM
gemm_thread_ram = [ 'gemm', 'gemm_ram', 'gemm_thread_ram' ]
gemm_stream_ram = [ 'gemm', 'gemm_ram', 'gemm_stream_ram' ]
gemm_thread_pipo = [ 'gemm', 'gemm_pipo', 'gemm_thread_pipo' ]

# SpMM
spmm_thread_ram = [ 'spmm', 'spmm_ram', 'spmm_thread_ram' ]
spmm_stream_ram = [ 'spmm', 'spmm_ram', 'spmm_stream_ram' ]
