pipos = [
  { name = 'ram_a', datawidth = 'packed_datawidth', addrwidth = 10 },
  { name = 'ram_b', datawidth = 'packed_datawidth', addrwidth = 10 },
  { name = 'ram_c', datawidth = 'datawidth', addrwidth = 10 },
]

comp_body = '''
chunk_num = size_1 >> log_parallelism
a_addr = a_offset
c_addr = c_offset
for i in range(size_0):
    ram_a.dma_read(maxi, 0, a_addr, chunk_num)
    b_addr = b_offset
    ram_a.read(0)
    ram_c.write(0, 0)
    for j in range(size_2):
        ram_b.dma_read(maxi, 0, b_addr, chunk_num)
        ram_b.read(0)
        strm.set_parameter('size', chunk_num)
        strm.set_source('a', ram_a, 0, chunk_num)
        strm.set_source('b', ram_b, 0, chunk_num)
        strm.set_sink('c', ram_c, j, 1)
        strm.run()
        strm.join()
        b_addr += size_1 * (datawidth // 8)
    ram_c.dma_write(maxi, 0, c_addr, size_2)
    a_addr += size_1 * (datawidth // 8)
    c_addr += size_2 * (datawidth // 8)'''
