# [ name, addrwidth ]
pipos = [
  [ 'ram_a', 10 ],
  [ 'ram_b', 10 ],
  [ 'ram_c', 10 ],
]

# [ name, datawidth ]
axis = [
  [ 'axi_a', 'datawidth' ],
  [ 'axi_b', 'datawidth' ],
  [ 'axi_c', 'datawidth' ],
]
