comp_body = '''
a_addr = a_offset
c_addr = c_offset
for i in range(size_0):
    ram_a.dma_read(axi_a, a_addr, size_1, size_1 >> 1)
    b_addr = b_offset
    for j in range(size_2):
        ram_b.dma_read(axi_b, b_addr, size_1, size_1 >> 1)
        strm.set_parameter('size', size_1)
        strm.set_source_buffet('a', ram_a, 0, size_1, release=(j == size_2 - 1))
        strm.set_source_buffet('b', ram_b, 0, size_1, release=True)
        strm.set_sink_buffet('sum', ram_c, j, 1, release=True)
        strm.run()
        strm.join()
        ram_b.rebase()
        b_addr += size_1 * (datawidth // 8)
    ram_a.rebase()
    ram_c.rebase()
    ram_c.dma_write(axi_c, c_addr, size_2, size_2 >> 1)
    a_addr += size_1 * (datawidth // 8)
    c_addr += size_2 * (datawidth // 8)'''
