rams = [
  { type = 'PIPO', name = 'ram_a', addrwidth = 10 },
  { type = 'PIPO', name = 'ram_b', addrwidth = 10 },
  { type = 'PIPO', name = 'ram_c', addrwidth = 10 },
]

axis = [
  [ 'axi_a', 'datawidth' ],
  [ 'axi_b', 'datawidth' ],
  [ 'axi_c', 'datawidth' ],
]
