rams = [
  { type = 'RAM', name = 'ram_a', datawidth = 'packed_datawidth', addrwidth = '10 - log_parallelism' },
  { type = 'RAM', name = 'ram_b', datawidth = 'packed_datawidth', addrwidth = '10 - log_parallelism' },
  { type = 'RAM', name = 'ram_c', datawidth = 'datawidth', addrwidth = 10 },
]

axis = [
  [ 'axi_narrow', 'datawidth' ],
  [ 'axi_wide', 'axi_wide_width' ],
]

comp_body = '''
chunk_num = size_1 >> log_parallelism
a_addr = a_offset
c_addr = c_offset
for i in range(size_0):
    axi_wide.dma_read(ram_a, 0, a_addr, chunk_num)
    b_addr = b_offset
    for j in range(size_2):
        axi_wide.dma_read(ram_b, 0, b_addr, chunk_num)
        strm.set_parameter('size', chunk_num)
        strm.set_source('a', ram_a, 0, chunk_num)
        strm.set_source('b', ram_b, 0, chunk_num)
        strm.set_sink('c', ram_c, j, 1)
        strm.run()
        strm.join()
        b_addr += size_1 * (datawidth // 8)
    axi_narrow.dma_write(ram_c, 0, c_addr, size_2)
    a_addr += size_1 * (datawidth // 8)
    c_addr += size_2 * (datawidth // 8)'''
