rams = [
  { type = 'RAM', name = 'ram_a_row', addrwidth = 10 },
  { type = 'RAM', name = 'ram_a_col', addrwidth = 10 },
  { type = 'RAM', name = 'ram_a_val', addrwidth = 10 },
  { type = 'RAM', name = 'ram_b', addrwidth = 10 },
  { type = 'RAM', name = 'ram_c', addrwidth = 10, numports = 2 },
]
