rams = [
  { type = 'RAM', name = 'ram_a_row', addrwidth = 10 },
  { type = 'PIPO', name = 'ram_a_col', addrwidth = 10 },
  { type = 'PIPO', name = 'ram_a_val', addrwidth = 10 },
  { type = 'PIPO', name = 'ram_b', addrwidth = 10 },
  { type = 'PIPO', name = 'ram_c', addrwidth = 10, numports = 2 },
]

axis = [
  [ 'axi_a_row', 'datawidth' ],
  [ 'axi_a_col', 'datawidth' ],
  [ 'axi_a_val', 'datawidth' ],
  [ 'axi_b', 'datawidth' ],
  [ 'axi_c', 'datawidth' ],
]
