# [ name, addrwidth ]
rams = [
  [ 'ram_a_row', 10 ],
]

# [ name, addrwidth, numports ]
pipos = [
  [ 'ram_a_col', 10 ],
  [ 'ram_a_val', 10 ],
  [ 'ram_b', 10 ],
  [ 'ram_c', 10, 2 ],
]

# [ name, datawidth ]
axis = [
  [ 'axi_a_row', 'datawidth' ],
  [ 'axi_a_col', 'datawidth' ],
  [ 'axi_a_val', 'datawidth' ],
  [ 'axi_b', 'datawidth' ],
  [ 'axi_c', 'datawidth' ],
]
